window.PACKAGES = window.PACKAGES || [];
window.PACKAGES.push(
{id:"geelong-banksia-1202",estate:"Banksia Estate",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"1202",design:"Fairlight 22",facade:"",land:394,home:null,beds:4,baths:2,living:2,cars:2,storeys:"Single storey",price:724088,priceType:"Fixed price",status:"Available",title:"",features:[],street:""},
{id:"geelong-banksia-1226",estate:"Banksia Estate",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"1226",design:"Nowra 24",facade:"",land:392,home:null,beds:4,baths:2,living:2,cars:2,storeys:"Single storey",price:740731,priceType:"From price",status:"Check availability",title:"",features:[],street:""},
{id:"geelong-banksia-1227",estate:"Banksia Estate",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"1227",design:"Jackalope 25",facade:"",land:396,home:null,beds:4,baths:3,living:2,cars:2,storeys:"Double storey",price:833501,priceType:"Fixed price",status:"Available",title:"",features:[],street:""},
{id:"geelong-coridale-1447-mundi",estate:"Coridale Estate",suburb:"Lara",area:"Geelong",state:"VIC",lot:"1447",design:"Mundi 22",facade:"",land:400,home:null,beds:4,baths:2,living:2,cars:2,storeys:"Single storey",price:672667,priceType:"Fixed price",status:"Available",title:"",features:[],street:""},
{id:"geelong-coridale-1447-cape",estate:"Coridale Estate",suburb:"Lara",area:"Geelong",state:"VIC",lot:"1447",design:"Cape 22",facade:"",land:400,home:null,beds:3,baths:2,living:2,cars:2,storeys:"Single storey",price:674571,priceType:"Fixed price",status:"Available",title:"",features:[],street:""},
{id:"geelong-mattana-104",estate:"Mattana Estate",suburb:"Mount Duneed",area:"Geelong",state:"VIC",lot:"104",design:"Gama 17",facade:"Summit",land:399,home:157,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:796050,priceType:"total price",status:"Expected title Oct-26",title:"Oct-26",features:["7 Star Energy Rating"],street:"Motion Dr"},
{id:"geelong-mattana-100-elwood",estate:"Mattana Estate",suburb:"Mount Duneed",area:"Geelong",state:"VIC",lot:"100",design:"Elwood 20",facade:"Duke",land:392,home:191,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:804050,priceType:"total price",status:"Expected title Oct-26",title:"Oct-26",features:["7 Star Energy Rating"],street:"Figwood St"},
{id:"geelong-mattana-100-heath",estate:"Mattana Estate",suburb:"Mount Duneed",area:"Geelong",state:"VIC",lot:"100",design:"Heath 21",facade:"Duke",land:392,home:196,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:811750,priceType:"total price",status:"Expected title Oct-26",title:"Oct-26",features:["7 Star Energy Rating"],street:"Figwood St"},
{id:"geelong-armstrong-waters-832",estate:"Armstrong Waters Estate",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"832",design:"Nexus 25 (Dual Key)",facade:"Egret",land:480,home:239,beds:6,baths:null,living:null,cars:null,storeys:"Single storey",price:972800,priceType:"total price",status:"Titled now",title:"Titled now",features:["5% Deposit","7 Star Rating"],street:"Barracouta Dr"},
{id:"geelong-warralily-12014",estate:"Warralily Estate",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"12014",design:"Elwood 20",facade:"Duke",land:400,home:191,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:782200,priceType:"total price",status:"Expected title Oct-27",title:"Oct-27",features:["7 Star Energy Rating"],street:"Esperance Ave"},
{id:"geelong-warralily-12015",estate:"Warralily Estate",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"12015",design:"Kennedy 22",facade:"Duke",land:400,home:207,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:799400,priceType:"total price",status:"Expected title Oct-27",title:"Oct-27",features:["7 Star Energy Rating"],street:"Esperance Ave"},
{id:"geelong-sanctuary-406",estate:"Sanctuary Springs Estate",suburb:"Leopold",area:"Geelong",state:"VIC",lot:"406",design:"Elwood 20",facade:"Duke",land:350,home:191,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:727390,priceType:"total price",status:"Expected title Jul-27",title:"Jul-27",features:[],street:"Garnet Close"},
{id:"geelong-haymont-802",estate:"Haymont Estate",suburb:"Charlemont",area:"Geelong",state:"VIC",lot:"802",design:"Elwood 20",facade:"Duke",land:350,home:191,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:772500,priceType:"total price",status:"Expected title Sep-27",title:"Sep-27",features:["7 Star Energy Rating"],street:"Theorem Ave"},
{id:"geelong-haymont-803",estate:"Haymont Estate",suburb:"Charlemont",area:"Geelong",state:"VIC",lot:"803",design:"Walker 20",facade:"Summit",land:350,home:180,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:773000,priceType:"total price",status:"Expected title Sep-27",title:"Sep-27",features:["7 Star Energy Rating"],street:"Theorem Ave"},
{id:"geelong-banksia-1308",estate:"Banksia",suburb:"Armstrong Creek",area:"Geelong",state:"VIC",lot:"1308",design:"Kennedy 22",facade:"President",land:494,home:207,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:832100,priceType:"total price",status:"Titled now",title:"Titled now",features:["7 Star Energy Rating"],street:"Goodenia St"},
{id:"geelong-leopold-green-1",estate:"Leopold Green",suburb:"Leopold",area:"Geelong",state:"VIC",lot:"1",design:"Drake 19",facade:"Duke",land:457,home:175,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:790100,priceType:"total price",status:"Titled now",title:"Titled now",features:[],street:"Cofferock Dr"},
{id:"geelong-leopold-green-10",estate:"Leopold Green",suburb:"Leopold",area:"Geelong",state:"VIC",lot:"10",design:"Elwood 20",facade:"Duke",land:457,home:191,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:809300,priceType:"total price",status:"Titled now",title:"Titled now",features:[],street:"Kensington Rd"},
{id:"geelong-silverbrook-1003",estate:"Silverbrook",suburb:"Mount Duneed",area:"Geelong",state:"VIC",lot:"1003",design:"Lucas 16",facade:"Summit",land:304,home:146,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:748700,priceType:"total price",status:"Expected title Jun-27",title:"Jun-27",features:[],street:"Mountain Ave"},
{id:"geelong-silverbrook-1007",estate:"Silverbrook",suburb:"Mount Duneed",area:"Geelong",state:"VIC",lot:"1007",design:"Elwood 20",facade:"Duke",land:392,home:191,beds:4,baths:null,living:null,cars:null,storeys:"Single storey",price:856300,priceType:"total price",status:"Expected title Jun-27",title:"Jun-27",features:[],street:"Roundleaf St"}
);
